version: '3.8'

services:
  phalcon-app:
    build: .
    container_name: phalcon4-project-aurora
    ports:
      - "8080:80"
    # extra_hosts:
    #   - "auroraphp.dev:127.0.0.1"
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      lokal:
        ipv4_address: 172.19.0.12

networks:
  lokal:
    external: true
    name: lokal
